version: '3.4'

services:

  backend:
    container_name: alp_backend_dev
    volumes:
      - ./backend:/opt/alp/backend

  frontend:
    container_name: alp_frontend_dev
    volumes:
      - ./frontend:/opt/alp/frontend

  nginx:
    container_name: alp_nginx_dev
    volumes:
      - ./config/nginx/conf.d/dev:/etc/nginx/conf.d
