version: '3.4'

services:

  frontend:
    volumes:
      - frontend_dist:/opt/alp/frontend/dist

  nginx:
    volumes:
      - ./config/nginx/conf.d/prod:/etc/nginx/conf.d
      - frontend_dist:/opt/alp/frontend/dist
