# Generated by Django 2.2.4 on 2019-08-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя ролла')),
                ('description', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Опциональное описание ролла')),
                ('uuid', models.CharField(db_index=True, max_length=64, verbose_name='Cinegy UUID')),
                ('category', models.CharField(max_length=64, verbose_name='Категория ролла')),
                ('start', models.DateTimeField(verbose_name='Время и дата начала')),
                ('end', models.DateTimeField(null=True, verbose_name='Время и дата окончания')),
            ],
            options={
                'unique_together': {('start', 'end', 'name', 'uuid', 'description')},
            },
        ),
    ]
