# Generated by Django 2.2.5 on 2019-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdby',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Исполнитель'),
        ),
    ]
